import { StyleSheet } from '@react-pdf/renderer';

export const createPdfStyles = (mode: 'luxury' | 'adventure') =>
  StyleSheet.create({
    page: {
      padding: 40,
      backgroundColor: mode === 'luxury' ? '#1A1A1A' : '#1F2937',
      fontFamily: 'Helvetica',
    },
    coverPage: {
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    logo: {
      marginBottom: 40,
    },
    coverTitle: {
      fontSize: 40,
      fontFamily: 'Helvetica-Bold',
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginBottom: 20,
      textAlign: 'center',
    },
    coverSubtitle: {
      fontSize: 20,
      color: '#FFFFFF',
      marginBottom: 40,
      textAlign: 'center',
    },
    accentBar: {
      width: 100,
      height: 4,
      backgroundColor: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginVertical: 20,
    },
    brandText: {
      fontSize: 12,
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      textAlign: 'center',
      marginTop: 40,
      fontFamily: 'Helvetica-Bold',
    },
    section: {
      marginBottom: 30,
    },
    sectionTitle: {
      fontSize: 24,
      fontFamily: 'Helvetica-Bold',
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginBottom: 15,
      paddingBottom: 5,
      borderBottomWidth: 1,
      borderBottomColor: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      borderBottomStyle: 'solid',
    },
    infoBox: {
      backgroundColor: '#2A2A2A',
      padding: 15,
      borderRadius: 5,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: mode === 'luxury' ? '#D4AF3733' : '#48BB7833',
      borderStyle: 'solid',
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#333333',
      borderBottomStyle: 'solid',
    },
    label: {
      color: '#888888',
      fontSize: 12,
    },
    value: {
      color: '#FFFFFF',
      fontSize: 12,
      fontFamily: 'Helvetica-Bold',
    },
    hotelCard: {
      backgroundColor: '#2A2A2A',
      padding: 20,
      borderRadius: 5,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: mode === 'luxury' ? '#D4AF3733' : '#48BB7833',
      borderStyle: 'solid',
    },
    hotelName: {
      fontSize: 16,
      fontFamily: 'Helvetica-Bold',
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginBottom: 8,
    },
    hotelDescription: {
      fontSize: 12,
      color: '#FFFFFF',
      marginBottom: 10,
      lineHeight: 1.4,
    },
    amenitiesList: {
      marginTop: 10,
    },
    amenityTag: {
      fontSize: 10,
      color: '#888888',
      marginBottom: 4,
    },
    priceInfo: {
      fontSize: 12,
      color: '#FFFFFF',
      marginTop: 10,
      fontFamily: 'Helvetica-Bold',
    },
    daySection: {
      backgroundColor: '#2A2A2A',
      padding: 20,
      borderRadius: 5,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: mode === 'luxury' ? '#D4AF3733' : '#48BB7833',
      borderStyle: 'solid',
    },
    dayTitle: {
      fontSize: 20,
      fontFamily: 'Helvetica-Bold',
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginBottom: 15,
    },
    activityTitle: {
      fontSize: 14,
      fontFamily: 'Helvetica-Bold',
      color: '#FFFFFF',
      marginBottom: 5,
    },
    activityDetails: {
      fontSize: 12,
      color: '#888888',
      marginBottom: 10,
      lineHeight: 1.4,
    },
    timeInfo: {
      fontSize: 11,
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginBottom: 5,
    },
    costInfo: {
      fontSize: 12,
      color: '#FFFFFF',
      marginTop: 5,
      fontFamily: 'Helvetica-Bold',
    },
    footer: {
      position: 'absolute',
      bottom: 30,
      left: 40,
      right: 40,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    footerText: {
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      fontSize: 10,
      fontFamily: 'Helvetica-Bold',
    },
    pageNumber: {
      fontSize: 10,
      color: '#666666',
    },
    bulletPoint: {
      fontSize: 12,
      color: '#FFFFFF',
      marginBottom: 4,
      paddingLeft: 15,
    },
    warningText: {
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      fontSize: 12,
      marginBottom: 8,
    },
    totalCost: {
      fontSize: 14,
      fontFamily: 'Helvetica-Bold',
      color: mode === 'luxury' ? '#D4AF37' : '#48BB78',
      marginTop: 10,
      textAlign: 'right',
    },
  });
